
download_home: None
data_root: data  # 存放数据的根目录，数据包括：预训练模型、训练和测试数据、保存模型

pre_trained_model:
    audio_encoder:
        ZH: weights/wav2emb_zh.onnx
        EN: weights/wav2emb_en.onnx
        RU: weights/wav2emb_ru.onnx
        PT: weights/wav2emb_pt.onnx
        ES: weights/wav2emb_es.onnx
        AR: weights/wav2emb_ar.onnx
        FR: weights/wav2emb_fr.onnx
        JA: weights/wav2emb_ja.onnx
    clusters:
        ZH: weights/emb2exp_zh_1024c.npz

